### ISSUE TITLE
overclocks dont work

### ISSUE THREAD

**Issue by RaisinJuice** [robertnunn/DRG-Save-Editor#13]
giving yourself overclocks does not work

**Comment by Hi-ImKyle** [comment]
It does, you need to forge one overclock in order for the overclock data entries to appear in your save file, otherwise the save editor doesn't know where to begin adding the overclocks.

I found this out by checking my save file before I had a forged overclock and there was no "ForgedSchematics" entry, after I forged one overclock legitimately and checked again there was and I was able to add all overclocks.

**Comment by robertnunn** [comment]
New OCs added and updated for U35
