### ISSUE TITLE
Data Cell value editing does not pass through to the game

### ISSUE THREAD

**Issue by feldsteina** [robertnunn/DRG-Save-Editor#24]
Basically the title, I edited the Data Cell number from 5 to 10, and I did not gain any Data Cell redemptions within DRG.
When I quit the game and re-opened the save file in the editor, it had reverted back to 5 Data Cells.
Furthermore, the Data Cell number did not change from 5 after I got a Data Cell through normal gameplay, which was expected to change the value to 6.
Please let me know if you need any further information.

**Comment by robertnunn** [comment]
The issue with not getting the redemptions (data cell -> scrip) was something I noticed during testing, but since it's possible to directly edit the amount of scrip I didn't think it was a priority.

As for the value not changing even after normal gameplay? Have you been playing a modded save? Because DRG now has separate saves for modded games, and you might be editing your vanilla save but loaded your modded one (or vice versa)? I could be mistaken but I think the other saves are in the same folder, but have the save name appended to the end of the filename.
