### ISSUE TITLE
Blank Cores Not Updating

### ISSUE THREAD

**Issue by airespenlaw** [robertnunn/DRG-Save-Editor#9]
Hi, 

I messaged you on Reddit today about this issue. When I update my blank core value, the new value doesn't stick. I've attached the save file (in a zipped folder because GitHub didn't like the original file). 

Thanks

[76561198264304915_Player.zip](https://github.com/robertnunn/DRG-Save-Editor/files/6175856/76561198264304915_Player.zip)

**Comment by robertnunn** [comment]
Does it retain the original value or does it change to a different one? If it changes to a different one, is it the same value every time?

**Comment by airespenlaw** [comment]
It retains the original value, regardless of the value I put in. I've only tried it when the original is at 0 or 1 cores.

**Comment by robertnunn** [comment]
Ok, I think I know what's happening. Your save has a 13th resource in the list of resources (jadiz, umanite, etc) when it normally has 12. This pushed the entry for blank cores outside a hardcoded range (which I'm updating to be dynamic instead of static). I should have an update pushed out in ~30 minutes or so.

**Comment by airespenlaw** [comment]
Rockin', thanks for the speedy response!

**Comment by robertnunn** [comment]
Just pushed an update, let me know if it works.

**Comment by airespenlaw** [comment]
All working great, thanks again!

**Comment by robertnunn** [comment]
Glad to hear it.
